### ISSUE TITLE
How to access Admin panel

### ISSUE THREAD

**Issue by schandra81** [pedropaf/saas-ecom-demo#1]
Hi,
I am following your code and trying to run in my machine. 
It looks like there is source code for admin panel.
Can you please direct me on this.

Thanks

**Comment by pedropaf** [comment]
Hi, there's no admin panel. As you can see in this form, there's only an area for registered users: http://www.pedroalonso.net/blog/2014/11/13/saas-ecom-available-in-nuget 

Thanks,
Pedro
